all:
		@docker-compose -f srcs/docker-compose.yml up --build

up:
		@docker-compose -f srcs/docker-compose.yml up --build

down:
		@docker-compose -f srcs/docker-compose.yml down

clean: down
		@docker system prune -a


fclean: down
		@chmod 744 clean.sh
		@sh clean.sh

info:
		@echo "=============================== IMAGES ==============================="
		@docker images
		@echo
		@echo "============================= CONTAINERS ============================="
		@docker ps -a
		@echo
		@echo "=============== NETWORKS ==============="
		@docker network ls
		@echo
		@echo "====== VOLUMES ======"
		@docker volume ls

.PHONY:	all up down clean info